name: Run Python Script Daily

on:
  schedule:
    - cron: '0 4 * * *'  # كل يوم الساعة 7 صباحًا بتوقيت السعودية (UTC+3 = 4 AM UTC)
  workflow_dispatch:     # لتشغيله يدويًا وقت ما تبين

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (if any)
      run: |
        pip install -r requirements.txt || echo "No requirements"

    - name: Run Python script
      run: python generate_report.py

    - name: Upload result file (log.txt)
      uses: actions/upload-artifact@v4
      with:
        name: report-log
        path: log.txt
